name 'olyn_system'
maintainer 'Scott Richardson'
maintainer_email 'dev@grogwood.com'
chef_version '~> 16'
license 'GPL-3.0'
supports 'debian', '>= 10'
source_url 'https://gitlab.com/olyn/olyn_system'
description 'Installs and configures system resources'
version '1.0.4'

provides 'olyn_system::default'
provides 'olyn_system::hosts'
provides 'olyn_system::packages'
provides 'olyn_system::ssl_certificates'
provides 'olyn_system::timezone'
provides 'olyn_system::users'
recipe 'olyn_system::default', 'Installs and configures system resources'
recipe 'olyn_system::hosts', 'Configures local hostnames and hostnames to other servers'
recipe 'olyn_system::packages', 'Installs required packages'
recipe 'olyn_system::ssl_certificates', 'Installs all SSl certificates from the SSL data bag'
recipe 'olyn_system::timezone', 'Sets the local timezone'
recipe 'olyn_system::users', 'Configures local system accounts and their SSH keys'
